### ISSUE TITLE
Use shorthand properties

### ISSUE THREAD

**Issue by trajano** [dealloc/vuec#7]
See https://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/

Instead of

```
Vue.$ioc.register('Axios', Axios);
```
we can use

```
Vue.$ioc.register( { Axios } ) ;
```

And for injection instead of  `created(SomethingThatMayGetMangled) { }` we can use `created( { SomethingThatWontGetMangled }) { }`

**Comment by dealloc** [comment]
That's actually a really great solution, I'll try to release an update making use of this soon!
